# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python_sandbox.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'python_sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14python_sandbox.proto\x12\x0epython_sandbox\"\x1a\n\nRunRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"4\n\x06Result\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\x05image\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_image\"V\n\x0bRunResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.python_sandbox.Result\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\"\x14\n\x12HealthcheckRequest\"\x15\n\x13HealthcheckResponse2\xa7\x01\n\rPythonSandbox\x12>\n\x03Run\x12\x1a.python_sandbox.RunRequest\x1a\x1b.python_sandbox.RunResponse\x12V\n\x0bHealthcheck\x12\".python_sandbox.HealthcheckRequest\x1a#.python_sandbox.HealthcheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=40
  _globals['_RUNREQUEST']._serialized_end=66
  _globals['_RESULT']._serialized_start=68
  _globals['_RESULT']._serialized_end=120
  _globals['_RUNRESPONSE']._serialized_start=122
  _globals['_RUNRESPONSE']._serialized_end=208
  _globals['_HEALTHCHECKREQUEST']._serialized_start=210
  _globals['_HEALTHCHECKREQUEST']._serialized_end=230
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=232
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=253
  _globals['_PYTHONSANDBOX']._serialized_start=256
  _globals['_PYTHONSANDBOX']._serialized_end=423
# @@protoc_insertion_point(module_scope)
