# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCode = channel.unary_unary(
                '/sandbox_grpc.Sandbox/RunCode',
                request_serializer=sandbox__pb2.RunCodeRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunCodeResponse.FromString,
                _registered_method=True)
        self.Healthcheck = channel.unary_unary(
                '/sandbox_grpc.Sandbox/Healthcheck',
                request_serializer=sandbox__pb2.HealthcheckRequest.SerializeToString,
                response_deserializer=sandbox__pb2.HealthcheckResponse.FromString,
                _registered_method=True)


class SandboxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthcheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCode': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCode,
                    request_deserializer=sandbox__pb2.RunCodeRequest.FromString,
                    response_serializer=sandbox__pb2.RunCodeResponse.SerializeToString,
            ),
            'Healthcheck': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthcheck,
                    request_deserializer=sandbox__pb2.HealthcheckRequest.FromString,
                    response_serializer=sandbox__pb2.HealthcheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox_grpc.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox_grpc.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox_grpc.Sandbox/RunCode',
            sandbox__pb2.RunCodeRequest.SerializeToString,
            sandbox__pb2.RunCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Healthcheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox_grpc.Sandbox/Healthcheck',
            sandbox__pb2.HealthcheckRequest.SerializeToString,
            sandbox__pb2.HealthcheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
