# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sandbox.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsandbox.proto\x12\x0csandbox_grpc\"\x1e\n\x0eRunCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"4\n\x06Result\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\x05image\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_image\"X\n\x0fRunCodeResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.sandbox_grpc.Result\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\"\x14\n\x12HealthcheckRequest\"\x15\n\x13HealthcheckResponse2\xa5\x01\n\x07Sandbox\x12\x46\n\x07RunCode\x12\x1c.sandbox_grpc.RunCodeRequest\x1a\x1d.sandbox_grpc.RunCodeResponse\x12R\n\x0bHealthcheck\x12 .sandbox_grpc.HealthcheckRequest\x1a!.sandbox_grpc.HealthcheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNCODEREQUEST']._serialized_start=31
  _globals['_RUNCODEREQUEST']._serialized_end=61
  _globals['_RESULT']._serialized_start=63
  _globals['_RESULT']._serialized_end=115
  _globals['_RUNCODERESPONSE']._serialized_start=117
  _globals['_RUNCODERESPONSE']._serialized_end=205
  _globals['_HEALTHCHECKREQUEST']._serialized_start=207
  _globals['_HEALTHCHECKREQUEST']._serialized_end=227
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=229
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=250
  _globals['_SANDBOX']._serialized_start=253
  _globals['_SANDBOX']._serialized_end=418
# @@protoc_insertion_point(module_scope)
